### ISSUE TITLE
Tracking convolution layers adapted to TemporalSnapshotsGNNGraphs 

### ISSUE THREAD

**Issue by rbSparky** [CarloLucibello/GraphNeuralNetworks.jl#394]
## Temporal Support for Graph Layers

This issue is meant to track the integration of temporal support for various graph layers. Each layer will be listed with a checkbox to indicate the progress of adding temporal support.

### Checklist

- [ ] GCNConv (WIP PR #392)
- [ ] ChebConv (WIP PR #393)
- [ ] GraphConv (WIP PR #392)
- [ ] GATConv (WIP PR #393)
- [ ] GATv2Conv (WIP PR #393)
- [ ] GatedGraphConv (WIP PR #393)
- [ ] EdgeConv
- [x] GINConv
- [ ] NNConv
- [ ] SAGEConv (WIP PR #392)
- [ ] ResGatedGraphConv (WIP PR #392)
- [ ] CGConv (WIP PR #393)
- [ ] AGNNConv
- [ ] MEGNetConv
- [ ] GMMConv
- [ ] SGConv (WIP PR #393)
- [ ] EGNNConv
- [ ] TransformerConv (WIP PR #393)
